# Generated by Django 5.2.3 on 2025-06-14 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=20, unique=True, verbose_name='Index Number')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Mrs.', 'Mrs.')], max_length=5)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name(s)')),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('ghana_card', models.CharField(help_text='e.g. GHA-12345789-1234', max_length=25, verbose_name='Ghana Card Number')),
                ('ssnit_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSNIT Number')),
                ('nationality', models.CharField(choices=[('GHANAIAN', 'GHANAIAN'), ('OTHER', 'OTHER')], max_length=20)),
                ('level', models.IntegerField(choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400')])),
                ('year_admitted', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('Other', 'Other')], max_length=10, verbose_name='Year Admitted')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deffered', 'Deffered'), ('Dismissed', 'Dismissed')], max_length=10, verbose_name='Student Status')),
                ('email', models.EmailField(max_length=254)),
                ('bank_branch', models.CharField(help_text='Where the account was created', max_length=100, verbose_name='Bank Branch')),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=20, verbose_name='Account Type')),
                ('account_number', models.CharField(max_length=20, verbose_name='Bank Account Number')),
                ('full_name', models.CharField(help_text='Full name as it appears on your bank account', max_length=200, verbose_name='Full Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formsapp.bank', verbose_name='Bank Name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formsapp.program', verbose_name='Program of Study')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsapp.survey')),
            ],
        ),
    ]
