# Generated by Django 5.2.3 on 2025-06-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_bank_program_and_survey_models_created'),
    ]

    def load_banks_data(apps, schema_editor):
        Bank = apps.get_model('formsapp', 'Bank')
        bank_data = [
        {"name": "Access Bank (Ghana)", "active": True},
        {"name": "ADB (Agricultural Development Bank)", "active": True},
        {"name": "Bank of Ghana (BOG)", "active": False},
        {"name": "Absa Ghana", "active": True},
        {"name": "CAL Bank", "active": True},
        {"name": "Ecobank Ghana", "active": True},
        {"name": "Fidelity Bank", "active": True},
        {"name": "GCB (Ghana Commercial Bank)", "active": True},
        {"name": "FAMB (First Atlantic Merchant Bank)", "active": True},
        {"name": "HFC", "active": False},
        {"name": "ICB (International Commercial Bank) Ghana", "active": False},
        {"name": "Universal Merchant Bank", "active": True},
        {"name": "NIB (National Investment Bank)", "active": True},
        {"name": "Prudential Bank", "active": True},
        {"name": "SG-SSB Limited", "active": True},
        {"name": "Guaranty Trust Bank Limited", "active": True},
        {"name": "GHIB (Ghana International Bank)", "active": False},
        {"name": "Enery Bank Ghana", "active": False},
        {"name": "Citibank NA Ghana", "active": False},
        {"name": "Stanbic Bank Ghana", "active": True},
        {"name": "BSIC Ghana", "active": True},
        {"name": "Standard Chartered Bank", "active": True},
        {"name": "TTB (The Trust Bank)", "active": False},
        {"name": "UniBank Ghana", "active": False},
        {"name": "United Bank for Africa (Ghana)", "active": True},
        {"name": "UT Bank Ghana Limited", "active": False},
        {"name": "Zenith Bank (Ghana)", "active": True},
        {"name": "Bank of Africa (Ghana)", "active": True},
        {"name": "Bank of Baroda (Ghana)", "active": False},
        {"name": "ARB Apex Bank", "active": False},
        {"name": "Consolidated Bank Ghana", "active": True},
        {"name": "FBNBank Ghana", "active": True},
        {"name": "First Atlantic Bank", "active": True},
        {"name": "Omni-BSIC Bank", "active": True},
        {"name": "GHL Bank", "active": True},
        {"name": "Republic Bank", "active": True},
    ]

        for bank in bank_data:
            Bank.objects.create(bank_name=bank['name'], active=bank['active'])

    operations = [
        migrations.RunPython(load_banks_data)
    ]
