# Generated by Django 5.2.3 on 2025-06-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0003_load_bank_data'),
    ]

    def load_program_data(apps, schema_editor):
        Program = apps.get_model('formsapp', 'Program')
        programs = [
    {'name': 'Certificate Disease Control (Field Technician)'},
    {'name': 'Certificate Health Records Management'},
    {'name': 'Diploma Registered Dental Surgery Assistantship'},
    {'name': 'Diploma Diagnostic Radiological Technology'},
    {'name': 'BSc. Physician Assistantship-Medical'},
    {'name': 'BSc. Disease Control'},
    {'name': 'BSc. Health Information Management'},
    {'name': 'BSc. Medical Laboratory Technology'},
    {'name': 'BSc. Registered Dental Surgery Assistantship'},
    {'name': 'BSc. Nutrition'},
    {'name': 'BSc. Health Promotion'},
    {'name': 'BSc. Physician Assistantship-Dental'},
    {'name': 'BSc. Community Mental Health'},
]
        for prog in programs:
            Program.objects.create(name=prog['name'])

    operations = [
        migrations.RunPython(load_program_data)
    ]

