# Generated by Django 5.2.3 on 2025-06-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_load_program_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='ghana_card',
            field=models.CharField(help_text='e.g. GHA-12345789-1', max_length=25, verbose_name='Ghana Card Number'),
        ),
    ]
