# Generated by Django 5.2.3 on 2025-06-15 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_ghana_card_field_helptext_rectified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='ghana_card',
            field=models.CharField(help_text='e.g. GHA-12345789-1', max_length=25, validators=[django.core.validators.RegexValidator(message='Ghana Card must follow the format: GHA-123456789-1', regex='^GHA-\\d{9}-\\d$')], verbose_name='Ghana Card Number'),
        ),
    ]
