# Generated by Django 5.2.3 on 2025-06-15 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0007_load_survey_initial_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='ghana_card',
            field=models.CharField(help_text='e.g. GHA-12345789-1', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Ghana Card must follow the format: GHA-123456789-1', regex='^GHA-\\d{9}-\\d$')], verbose_name='Ghana Card Number'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='ssnit_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SSNIT Number'),
        ),
    ]
