# Generated by Django 5.2.3 on 2025-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0008_ghana_card_email_and_account_number_made_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the survey is currently active', verbose_name='Active Survey'),
        ),
    ]
